Fix and update
SynergiTech/laravel-alert pull request #1
Opened 2019-09-24 09:37 UTC by willpower232

Found a facade bug whilst testing laravel 6, seems to work though

2019-09-24 12:37 UTC, Josh-G requested changes

2019-09-24 12:37 UTC, Josh-G commented on composer.json
> +        "illuminate/support": "~5.0|^6.0",
does this work? i thought it was `~5.0 || ^6.0`? lets also change the tilde to a caret

2019-09-24 13:55 UTC, willpower232 commented on composer.json
> +        "illuminate/support": "~5.0|^6.0",
citation from faux upstream: https://github.com/uxweb/sweet-alert/blob/7cf30629eb6c07b887a61d1879631f32fb9376da/composer.json#L14

2019-09-25 08:55 UTC, Josh-G approved these changes

2019-09-25 08:56 UTC, merged